version: '3'

services:
  app:
    image: node:lts
    working_dir: /home/node/app
    command: npm run start:debug
    user: node
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env.development.local
    volumes:
      - ./.docker/dbdata:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./.docker/rabbitmq:/var/lib/rabbitmq
