version: '3'

services:
  app_test:
    build: .
    entrypoint: wait-for db_test:3306 -t 40 -- .docker/test/entrypoint.sh
    volumes:
      - .:/home/node/app
    depends_on:
      - db_test

  db_test:
    image: mysql:5.7
    ports:
      - 3307:3306
    env_file:
      - .env.test
